parameters:
#    utilisateurs.example.class: Utilisateurs\UtilisateursBundle\Example

services:
    user.form.registration:
        class: Utilisateurs\UtilisateursBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: user_registration}


